"""
Collaborative Tasks Package

This package manages multi-agent collaborative tasks generated by the FSM system.
"""

from .collaborative_task_manager import (
    CollaborativeTaskManager,
    CollaborativeTask,
    CollaborativeTaskType,
    CollaborativeTaskState,
    AgentContribution
)

from .collaborative_orchestrator import CollaborativeOrchestrator

__all__ = [
    "CollaborativeTaskManager",
    "CollaborativeTask", 
    "CollaborativeTaskType",
    "CollaborativeTaskState",
    "AgentContribution",
    "CollaborativeOrchestrator"
]

